---
title: "Height_Length_Weight_Correlation"
author: "Becca Cates"
date: "2025-06-16"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = TRUE)
```

# Library

```{r, include=FALSE}
library(ggplot2)
library(tidyverse)
library(ggpubr)
```

# Read in data

```{r, include=FALSE}
oyster <- read.csv("../Data/EVOS Oyster morphometrics.csv")
```

# Clean and prep data

```{r, include=FALSE}
str(oyster)

#create subset of data
oyster <- dplyr::select(oyster, c("Sample_event", "Sample_date", "Region", "Farm", "Oyster_age", "Shell_height_mm", "Shell_length_mm", "Shell_depth_mm", "Whole_weight_g", "Meat_weight_g"))

#change str of data
oyster$Sample_date <- as.Date(oyster$Sample_date, "%m/%d/%Y")
oyster$Meat_weight_g <- as.numeric(oyster$Meat_weight_g)
oyster$Whole_weight_g <- as.numeric(oyster$Whole_weight_g)
oyster$Shell_depth_mm <- as.numeric(oyster$Shell_depth_mm)
oyster$Shell_length_mm <- as.numeric(oyster$Shell_length_mm)
oyster$Sample_event <- as.factor(oyster$Sample_event)
oyster$Shell_height_mm <- as.numeric (oyster$Shell_height_mm)

#create subadult and juvenile dfs
subadult <- dplyr::filter(oyster, Oyster_age == "Subadult")
juvenile <- dplyr::filter(oyster, Oyster_age == "Juvenile")
```

# Subadult correlations

#### **(Height, weight, length, cup ratio, whole weight, meat weight)**

```{r echo=FALSE, warning=FALSE, message=FALSE}
ggscatter(subadult, x = "Shell_height_mm", y = "Shell_length_mm", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Shell Height (mm)", ylab = "Shell Length (mm)")
#R=0.69

ggscatter(subadult, x = "Shell_height_mm", y = "Shell_depth_mm", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Shell Height (mm)", ylab = "Shell depth (mm)")
#R=0.49

ggscatter(subadult, x = "Shell_length_mm", y = "Shell_depth_mm", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Shell length (mm)", ylab = "Shell depth (mm)")
#R=0.56

ggscatter(subadult, x = "Whole_weight_g", y = "Meat_weight_g", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Whole weight (g)", ylab = "Meat weight (g)")
#R=0.87

ggscatter(subadult, x = "Whole_weight_g", y = "Shell_height_mm", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Whole weight (g)", ylab = "Shell height (mm)")
#R=0.85

#corrgram
library(corrgram)
corrgram(subadult, order=TRUE, lower.panel=panel.shade,
  upper.panel=panel.pie, text.panel=panel.txt,
  main="Subadult oyster")

```

# Juvenile correlations

```{, recho=FALSE, warning=FALSE, message=FALSE}
ggscatter(juvenile, x = "Shell_height_mm", y = "Shell_length_mm", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Shell Height (mm)", ylab = "Shell Length (mm)")
#R=0.79

ggscatter(juvenile, x = "Shell_height_mm", y = "Shell_depth_mm", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Shell Height (mm)", ylab = "Shell depth (mm)")
#R=0.71

ggscatter(juvenile, x = "Shell_length_mm", y = "Shell_depth_mm", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Shell length (mm)", ylab = "Shell depth (mm)")
#R=0.64

ggscatter(juvenile, x = "Whole_weight_g", y = "Meat_weight_g", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Whole weight (g)", ylab = "Meat weight (g)")
#R=0.87

ggscatter(juvenile, x = "Whole_weight_g", y = "Shell_height_mm", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Whole weight (g)", ylab = "Shell height (mm)")
#R=0.86

#Corrgram
library(corrgram)
corrgram(juvenile, order=TRUE, lower.panel=panel.shade,
  upper.panel=panel.pie, text.panel=panel.txt,
  main="Juvenile oyster")
```

```{r, include = FALSE}
# A function for captioning and referencing images
fig <- local({
    i <- 0
    ref <- list()
    list(
        cap=function(refName, text) {
            i <<- i + 1
            ref[[refName]] <<- i
            paste("Figure ", i, ": ", text, sep="")
        },
        ref=function(refName) {
            ref[[refName]]
        })
})

# Creates custom base plot theme that can adjust every graph that you use plot_theme for!

plot_theme <- function() {
  theme_bw(base_size = 14, base_family = "Avenir") %+replace%
    theme(panel.background  = element_blank(),
            plot.background = element_rect(fill="gray96", colour=NA), 
            legend.background = element_rect(fill="transparent", colour=NA),
            legend.key = element_rect(fill="transparent", colour=NA),
            panel.grid.major = element_blank(), 
            panel.grid.minor = element_blank(),
            strip.background = element_rect(colour = "NA", fill = "gray96"))
}
```
